version: '3.8'
services:
  redis:
    image: redis:7
    container_name: ruggine-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
